---
title: "Lab 2 Reflection"
description: "Here I reflect on my E155 lab 2 experience and my growth since lab 1"
author: "Thomas Lilygren"
date: "9/9/25"
categories:
  - reflection
  - labreport
draft: false
---

After completing lab 1, I felt that I had more of a grasp effort, dedication, and time required to complete this lab to the best of my abilities. I set aside of bulk of my time to work on this lab, while still designating enough time for my other work and commitments. I had a hard time grasping the overall flow of how a time-multiplexer works and how it should be implemented, but thanks Xavier's clear explanation, I felt the Verilog aspect was not as difficult as I initially assumed. I ran into an odd issue where a majority of the inputs displayed the correct values, but experienced an odd behavior at a few specific combinations. I spent hours trying to debug what was seemingly a hardware issue, but thankfully, a superb grutor, Troy, experienced the same issue I had when he worked on this lab. The issue was that the internal pull-up resistor was too weak and caused a latching behavior. By editing the internal pullup resistor in the Device Constraint Editor, my problem was miraculously solved! Additionally, my experience with testbenches typically involved test vectors, so to test all 256 possible switch combinations for the led sum logic, I manually wrote out close to 200 of them before realizing that there must be a better way. I learned how to write testbenches with assert statements and implemented my first successful iterating for loops in my multiplexer testbench. These experiences, while time-consuming in the moment, added more debugging tools that I can rely on in the future.  

I've heard many warnings about lab 3, but I feel confident that I can get through it. There were many times this lab and the last one where I felt like giving up and that I was in over my head, but ultimately, I found a way to get through. I am extremely grateful for my peers, Prof. Spencer, Xavier, and the grutors for helping me walk through certain steps and explaining concepts I initially found perplexing. Lab 3 strikes at an inconvenient time for me, since I have a project deliverable and clinic design review presentation due around the same time as my check-in, but I plan to get an early start, plan out my time to satisfy all commitments, and still allocate time for personal health, like exercising. I am proud of myself for these first two labs, and I maintain that feeling throughout the semester.